### ISSUE TITLE
Multiple tokens

### ISSUE THREAD

**Issue by NoelSMartin** [fastify/fastify-jwt#172] opened 2021-08-18 14:28 UTC
## 🚀 Feature Proposal

The ability to generate multiple tokens. 

## Motivation

To be able to implement the Access and Refresh token concepts

**Comment by climba03003** [comment] 2021-08-18 14:55
I don't really know what do you means. `jwt` can be generated for multiple token. If you need different key / secret. It should be duplicate of #111 .

**Comment by darkgl0w** [comment] 2021-10-30 08:48
We can close this as it is a duplicate of https://github.com/fastify/fastify-jwt/issues/111

You can now register multiple namespaced instances of this plugin and implement this use case.

**Closed** 2021-10-30 08:59 UTC

**Comment by eugenkur** [comment] 2025-01-25 19:44
hello! i write it becouse try to find how i can use some of tokens (chatGPT help me falsely). 
i use it like plugin, so there is example:
`async function jwt(instance){
    instance.register(fastifyJwt, {
        secret: 'secretClient',
        namespace: 'client',
        jwtVerify: 'clientVerify',
        jwtSign: 'clientSign'
    })
    instance.register(fastifyJwt, {
        secret: 'secretAPI',
        namespace: 'api',
        jwtVerify: 'apiVerify',
        jwtSign: 'apiSign'
    })

    instance.decorate('jwtClient', async (req, reply) => {
        try{
            console.log(req)
            await req.clientVerify()
        } catch(err) {
            reply.send(err)
        }
    })
    instance.decorate('jwtAPI', async (req, reply) => {
        try{
            await req.apiVerify()
        } catch(err) {
            reply.send(err)
        }
    })
}

export default fastifyPlugin(jwt)`

After register it on fastify and then use it like this:
```
fastify.get('/packages', {schema: getAllPackagesSchema, onRequest: fastify.jwtAPI}, async (req, reply) => {
        //возвращение всех пакетов
        return 'hello all packages, ' + req.user //req.user - data from JWT
    })
```
